shared:
  group_name: /k8s-learn
env:
  docker_ce_repo_url: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  docker_version: 19.03.13-3.el7
  docker_mirror_url: https://xywhyayv.mirror.aliyuncs.com
